# Generated by Django 5.2.10 on 2026-03-10 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
