# Generated by Django 5.2.10 on 2026-03-19 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.reg_users'),
            preserve_default=False,
        ),
    ]
