# Generated by Django 5.2.10 on 2026-04-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goal',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
