# Generated by Django 5.2.10 on 2026-03-10 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='user',
            new_name='user_id',
        ),
    ]
