# Generated by Django 5.2.10 on 2026-03-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_budget_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.CharField(max_length=7),
        ),
    ]
