# Generated by Django 5.2.10 on 2026-03-26 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_budget_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='category',
        ),
    ]
