# Generated by Django 5.2.10 on 2026-04-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_goal_is_completed_goal_target_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='feedback',
            name='type',
            field=models.CharField(default=5, max_length=20),
            preserve_default=False,
        ),
    ]
